### ISSUE TITLE
Denoise scheduler & cfg scheduler hook don't seem to work with TiledKSampleUpscalerProvider

### ISSUE THREAD

**Issue by Rkkss** [ltdrdata/ComfyUI-extension-tutorials#10]
works with regular ksample upscaler node but not tiled ksample upscaler
It's supposed to be like this probably? but the availability of Pk_hook_opt input got me confused anyway

**Comment by ltdrdata** [comment]
I missed this issue. I have confirmed that it is now working without errors when using the latest version of the Impact Pack and Tiled KSampler. If there are any problems, please reopen it.
