### ISSUE TITLE
Weighted choices in wildcard selection

### ISSUE THREAD

**Issue by Kextrii** [ltdrdata/ComfyUI-extension-tutorials#11]
Is there an option to weight choices differently within a wildcard selection?

e.g. adieyal/sd-dynamic-prompts allows the following syntax:
{0.25::spring|0.125::summer|0.25::autumn|0.375::winter}
or
{2::spring|1::summer|2::autumn|3::winter}

So that summer is chosen the least, winter the most, and spring or autumn chosen more than summer but less than winter.

In the dynamic-prompts implementation, it doesn't matter if the weights add up to 1 or some other number -- it will normalize them.

**Comment by ltdrdata** [comment]
This is implemented on 7a80d0b3f5ea04ee9ac9cec9e2dbc0281d606994

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md
