### ISSUE TITLE
Facedetailer broken with the "simple" 

### ISSUE THREAD

**Issue by Charuru** [ltdrdata/ComfyUI-extension-tutorials#12]
![Screenshot 2023-08-05 180045](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/214436/95a93793-ba0b-4777-814e-4eaf81fe386f)

Can you explain how to apply the 3 missing arguments?

While this example doesn't have those arguments as node points, adding a new facedetailer does, but I don't know what goes into them?

'guide_size_for', 'noise_mask', and 'force_inpaint'

**Comment by ltdrdata** [comment]
You need to update ComfyUI and Impact Pack to latest version.
