### ISSUE TITLE
Error loading reencode-workflow.json

### ISSUE THREAD

**Issue by delcompan** [ltdrdata/ComfyUI-extension-tutorials#13]
Error loading reencode-workflow.json:

When loading the graph, the following node types were not found:
## sdxl-ksample [3c7e70]
Nodes that have failed to load will show as red on the graph.

The impact pack doesn't seem to have these nodes

**Comment by ltdrdata** [comment]
They are not belongs to Impact Pack.

They are components from
https://github.com/ltdrdata/ComfyUI-Workflow-Component

**Comment by delcompan** [comment]
Thank you.

**Comment by fuselayer** [comment]
> They are not belongs to Impact Pack.
> 
> They are components from https://github.com/ltdrdata/ComfyUI-Workflow-Component

Never mind, sorry. I just had to replace the nodes manually. They're installed. 

<s>I installed this, but I'm still getting an error that the basic pipe components for sdxl and refiner are missing:

![image](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/145614503/bc36756c-7efc-4dc9-8780-a5e7e6e18e96)</s>

**Comment by vealo9** [comment]
What do you mean by replacing them manually? I'm having the same issue.

**Comment by ltdrdata** [comment]
> What do you mean by replacing them manually? I'm having the same issue.

That is just a simple abbreviation of VAE Decode -> VAE Encode.
