### ISSUE TITLE
Please provide a update to onnx tutorial

### ISSUE THREAD

**Issue by MoonMoon82** [ltdrdata/ComfyUI-extension-tutorials#2]
Could you please provide an updated version of the onnx tutorial 
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ONNX.md
which doesn't seem to work anymore - even with new or old/legacy nodes I get error
![grafik](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/41437842/09ffc738-0a7d-482d-9da9-a17d3d21e871)

Great work!!

**Comment by Pos13** [comment]
I tried 7 different models, but only NudeNet (from example) works. Did it work with any other model beforehand?

**Comment by ltdrdata** [comment]
> I tried 7 different models, but only NudeNet (from example) works. Did it work with any other model beforehand?

There is a wide variety of ONNX models. The currently implemented OnnxDetectorProvider was created simply in response to the request for nudetnet support. There is no existing investigation on other models with the same concept.
Furthermore, it has been confirmed that ONNX package doesn't support Python 3.11, so currently, there is only minimal support for the ONNX side.
