### ISSUE TITLE
nvmd,my bad

### ISSUE THREAD

**Issue by OtakuFra** [ltdrdata/ComfyUI-extension-tutorials#26]
sorry, mistake

**Comment by emmanuel-a-otchere** [comment]
what was the solution? Getting similar

**Comment by ltdrdata** [comment]
> what was the solution? Getting similar

You need to see terminal log.

**Comment by OtakuFra** [comment]
> what was the solution? Getting similar

there was a second deprecated node hidden behind another node, i found it right after opening the ticket
