### ISSUE TITLE
Detailer Cropped vs Cropped Refined?

### ISSUE THREAD

**Issue by ckao10301** [ltdrdata/ComfyUI-extension-tutorials#28]
Cropped Refined result looks better than Cropped, but Cropped Refined is not getting applied to the final image-it appears that Cropped is being applied instead. Is that intended? What's the difference between Cropped and Cropped_refined?

<img width="884" alt="image" src="https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/129625358/be85dac9-10ab-41b3-a9b5-13fdaddf5483">

**Comment by ltdrdata** [comment]
Increase the "denoise" to 1.0, and you should be able to clearly identify what has been applied.
Also, to easily check the range of the applied image, it provides "cropped_refined_alpha." Take a look at that.

**Comment by ckao10301** [comment]
Hmmm, now that I'm considering the "cropped_refined_alpha", I can't tell which one is being applied. I just thought the blending on cropped_refined looked better. What exactly is the difference between "cropped" and "cropped refined"?

<img width="991" alt="image" src="https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/129625358/29acf8bd-748a-4074-9790-e50f95d7d1c2">

**Comment by ltdrdata** [comment]
> Hmmm, now that I'm considering the "cropped_refined_alpha", I can't tell which one is being applied. I just thought the blending on cropped_refined looked better. What exactly is the difference between "cropped" and "cropped refined"?
> 
> <img alt="image" width="991" src="https://private-user-images.githubusercontent.com/129625358/295142662-29acf8bd-748a-4074-9790-e50f95d7d1c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDYwMTksIm5iZiI6MTcwNDgwNTcxOSwicGF0aCI6Ii8xMjk2MjUzNTgvMjk1MTQyNjYyLTI5YWNmOGJkLTc0OGEtNDA3NC05NzkwLWU1MGY5NWQ3ZDFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMzA4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQ1OWMzM2M4MzcwNjA1MjljZDc0Njk4YWE5Y2U2ODgzYTA5NTQ0YTgzNGUwMDA5NzUzMmFkOTcwZjdmODU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uNhE7pBNdAj_sJK1FNswiL71nIOBfaSUbiy9wAta9Wo">

That's definitely a bug. "cropped" should display the original as it is, but it seems that the refined result is effecting to cropped, too.

**Comment by ltdrdata** [comment]
I just tested it, but I don't experience such symptoms. Could you please share your workflow with me?

**Comment by ckao10301** [comment]
> > Hmmm, now that I'm considering the "cropped_refined_alpha", I can't tell which one is being applied. I just thought the blending on cropped_refined looked better. What exactly is the difference between "cropped" and "cropped refined"?
> > <img alt="image" width="991" src="https://private-user-images.githubusercontent.com/129625358/295142662-29acf8bd-748a-4074-9790-e50f95d7d1c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDYwMTksIm5iZiI6MTcwNDgwNTcxOSwicGF0aCI6Ii8xMjk2MjUzNTgvMjk1MTQyNjYyLTI5YWNmOGJkLTc0OGEtNDA3NC05NzkwLWU1MGY5NWQ3ZDFjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQxMzA4MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzQ1OWMzM2M4MzcwNjA1MjljZDc0Njk4YWE5Y2U2ODgzYTA5NTQ0YTgzNGUwMDA5NzUzMmFkOTcwZjdmODU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uNhE7pBNdAj_sJK1FNswiL71nIOBfaSUbiy9wAta9Wo">
> 
> That's definitely a bug. "cropped" should display the original as it is, but it seems that the refined result is effecting to cropped, too.

Yes, from my experience "cropped" doesn't show the original image, it shows the newly generated image. Here are the input images and workflow json is below.

![coworkers (45)](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/129625358/9cfbd226-ead6-44f8-aaa1-935229f00cef)
![mask_00023_ (4)](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/129625358/a50c9a67-fc98-45bf-8027-9a484d371d27)
[_test workflow.json](https://github.com/ltdrdata/ComfyUI-extension-tutorials/files/13881734/_test.workflow.json)

**Comment by 12309kajsd8123b** [comment]
Hi. I think I have re-created this issue in my instance. 
From the magnified view it is clear that the cropped view gets applied, not cropped refined.
There is a clear line of skin tone difference under the chin that is only visible on the cropped version.
![screen](https://github.com/user-attachments/assets/6f0860aa-67d5-45ae-a790-522c4d37cc1d)
![example](https://github.com/user-attachments/assets/b2645ec3-ae6e-492d-b699-afa1cdb2f245)

**Comment by ltdrdata** [comment]
This is fixed.
