### ISSUE TITLE
It fails to interpret some of the wildcards inside a wildcard.

### ISSUE THREAD

**Issue by LuisBurdallo** [ltdrdata/ComfyUI-extension-tutorials#29]
This is the output. It seems at some point it gets confused and it shows the wildcard file name name instead. It works perfectly fine in A1111. The thing is that it seems to read some of the files inside that folder just fine but when it reaches that point as you can see in the screenshot it can't solve it as it should.

This is the part where it fails:

 __vogonic_guide/name-beast__,
 __vogonic_guide/name-beast-suf

As you see the folder named vogonic_guide folder shows up instead of the text inside the wildcards text file content inside.
![Snippet_008](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/33180658/2f2368e2-cab6-471d-8512-c4f304b88d1c)

![Snippet_007](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/33180658/695d32de-b999-4297-9aac-4ccef665b679)

**Comment by LuisBurdallo** [comment]
I found the issue and it was inside the name-beast.txt file where there was a simple missing space between 2 different wildcards calling. Weird that it wasn't a problem in A1111. You can close this. Sorry for not seeing that before posting.

**Comment by ltdrdata** [comment]
In my implementation, there are some limitations for clarity.
