### ISSUE TITLE
Cannot start face-detailer-start.json

### ISSUE THREAD

**Issue by todhm** [ltdrdata/ComfyUI-extension-tutorials#3]
I want to make worfklow like [face-detailer-start.png](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Workflow-Component/images/face-detailer-start.png)
However If i load face-detailer-start.json i2i-startpixel and face-detailer-start node cannot be loaded how could I fix this?

**Comment by ltdrdata** [comment]
Update your `Comfyui-Workflow-Component` (0.39.6) and `ComfyUI-Impact-Pack` (2.22) to latest version.
If you are still experiencing the same symptoms, please capture the console logs and send them to me.

**Comment by todhm** [comment]
Thanks a lot now it seems work.
