### ISSUE TITLE
Images with ImpactWildcardProcessor have no generation data on CiviAI

### ISSUE THREAD

**Issue by andreszs** [ltdrdata/ComfyUI-extension-tutorials#33]
Whenever the [ImpactWildcardProcessor](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/ImpactWildcard.md) node is used in the workflow to load wildcards from text files, the generation prompt is not retrieved when the image is uploaded on CivitAi.

I'm not sure if this is an error on their side, or if the node is messing around with the generation data. [Here's](https://www.metadata2go.com/result#j=cee64f05-479b-45a6-b608-705f2f240905) the metadata from a sample uploaded image that CivitAi failed to read.

**Comment by ltdrdata** [comment]
CivitAi's ability to interpret metadata is very limited. There's no way around this issue.
