### ISSUE TITLE
ImpactWildcardEncode populated prompt not working

### ISSUE THREAD

**Issue by CocoPuffLeo** [ltdrdata/ComfyUI-extension-tutorials#38]
I added texts into the text box with correct wildcard settings yet the populated prompt didn't show anything during the render process. more over the result is completely wrong. Somthing I am missing? Also how can i remove the select to add lora and wildcard at the bottom?

![awdawdwad](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/120401853/ecf618c3-4bd6-4576-8d42-0e90a0184052)

**Comment by ltdrdata** [comment]
The `seed` of a wildcard node is very limited in its use.
That allows only `Impact Int`, `Seed (rgthree)` and `Primitive`.

Make sure that.

**Comment by CocoPuffLeo** [comment]
I see, I used an alternative work around, as I still could not figure out how to solve this issue. Thank you for the response anyway.

**Comment by lucklobster** [comment]
I'm the having the same or similar issue.

In one of my workflows, this node will not populate, but in another workflow with the exact same seed generation & prompt setup, it does work.

If I switch the seed on the ImpactWildcardEncode from "input" back to "widget" in the non-functioning workflow, it will populate, but not if the seed is supplied externally. I am using the ImpactInt node to generate the seed.

What else could be causing the lower field not to populate?
