### ISSUE TITLE
Dynamic prompt using the format {a|b|c} no longer works in ImpactWildcardprocessor and encode?

### ISSUE THREAD

**Issue by CocoPuffLeo** [ltdrdata/ComfyUI-extension-tutorials#39]
After recent update (five days ago) the ImpactWildcardprocessor and encode no longer respond to the dynamic prompts using this format {a|b|c}. Wildcard is still usable but not the dymanic prompts. If their an update issue that cause this function to be disabled? or was there any update issue? Or have I done something wrong here.

**Comment by ltdrdata** [comment]
The ImpactWildcardProcessor has the dynamicPrompt feature disabled from the start, so it is not affected. The results of the test I just conducted also show no problems.

![image](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/128333288/4fa422a4-36f5-4241-98c9-eee0f0dbd8a3)
![image](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/128333288/b09bab90-fd48-4e41-835e-17499185ab3b)

**Comment by CocoPuffLeo** [comment]
This is weird, changing the seed to input can cause the dynamic prompt to stop working? Also I do no't know why but it seems the processor is quite unstable cause now the wildcard is no longer working. 
If I do not change the seed to input dynamic prompt works.

**Comment by ltdrdata** [comment]
> This is weird, changing the seed to input can cause the dynamic prompt to stop working? Also I do no't know why but it seems the processor is quite unstable cause now the wildcard is no longer working. 
> If I do not change the seed to input dynamic prompt works.

Disable all other nodes and try again.

**Comment by CocoPuffLeo** [comment]
Thank you Very much for your help and patiences, it turns out that having empty space between words in wildcard's name is not allowed, as the impact nodes won't read it. I removed the space and it works again.

**Comment by ltdrdata** [comment]
> Thank you Very much for your help and patiences, it turns out that having empty space between words in wildcard's name is not allowed, as the impact nodes won't read it. I removed the space and it works again. 

Oh...Yeah. That is a limitation for clear intpretation.

That's good.
