### ISSUE TITLE
Every time I run tutorial I just get black image

### ISSUE THREAD

**Issue by todhm** [ltdrdata/ComfyUI-extension-tutorials#4]
The only warning message I have is following everything else works fine. 
Do you have any idea?
```
custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py:334: RuntimeWarning: invalid value encountered in cast
  image = np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8)
invalid value encountered in cast
  image = np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8)
```

**Comment by ltdrdata** [comment]
Is it occurred from all workflow of tutorial?
Have you tried on default workflow?

**Comment by todhm** [comment]
I don't know what you mean by default workflow. 
It does not work on simple.json/ i2i.json
but it does not work on basic-refine.json/ face-detailer-start.json /faceswap.json/TwoSamplersForMask.json etc.

**Comment by ltdrdata** [comment]
> I don't know what you mean by default workflow. It does not work on simple.json/ i2i.json but it does not work on basic-refine.json/ face-detailer-start.json /faceswap.json/TwoSamplersForMask.json etc.

I meant ComfyUI's default workflow.

**Comment by todhm** [comment]
I don't know what you mean by default workflow. 

sorry it does not work either
invalid value encountered in cast
  img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
  Error still exists.

**Comment by ltdrdata** [comment]
> img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))

If the default workflow is not working properly, you need to address that issue. It's possible that the problem is being caused by other custom nodes.

First, rename the custom_nodes directory and create an empty custom_nodes directory to verify if it functions correctly.

If there are no issues, you'll need to gradually move the custom nodes back into the directory one by one to identify which one is causing the problem.

**Comment by LeeRuJun** [comment]
comfyui-animatediff/animatediff/nodes.py:169: RuntimeWarning: invalid value encountered in cast
  img = Image.fromarray(np.clip(img, 0, 255).astype(np.uint8))

i alse suffered this question, so bad

**Comment by ltdrdata** [comment]
> comfyui-animatediff/animatediff/nodes.py:169: RuntimeWarning: invalid value encountered in cast img = Image.fromarray(np.clip(img, 0, 255).astype(np.uint8))
> 
> i alse suffered this question, so bad

That is related to animatediff.
And I recommend `https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved` instead of original animatediff.

**Comment by LeeRuJun** [comment]
3q, done as your advice,  but question still exits

**Comment by lastYoueven** [comment]
i get same issues, the default workflow is allrigth, i pull images png form stable diffusion gen, i got the image all black. 
someone have any ideas?

**Comment by MattaTatTat76** [comment]
I have the same exact issue as todHM. I switched to an empty node directory but it didn't solve the issue so it's not the nodes that are causing the problem. Any other ideas?

**Comment by ltdrdata** [comment]
> I have the same exact issue as todHM. I switched to an empty node directory but it didn't solve the issue so it's not the nodes that are causing the problem. Any other ideas?

If your machine mac then check this.
https://github.com/comfyanonymous/ComfyUI/issues/3521
