### ISSUE TITLE
Each Image Frame's Mask Is Combined and Applied to All Images When using "MASK to SEGS for AnimateDiff" and "Detailer For AnimateDiff(SEGS/pipe)"

### ISSUE THREAD

**Issue by Misukokonmilk** [ltdrdata/ComfyUI-extension-tutorials#44]
Thanks for your amazing nodes, it works very well in my single image tasks. But I am confused when using them with AnimateDiff.

I iterated through every frame of the video and obtained the desired masks using Segment anything, which I saved as images. However, when using AnimateDiff, I selected 8 mask images to convert into masks and fed them into 'MASK to SEGS for AnimateDiff', which then provided the input for 'Detailer For AnimateDiff(SEGS/pipe)'. But I noticed that instead of the input segs being used for the corresponding frame, they were combined and applied to every frame of the video.

I have reviewed the documentation and watched the videos you provided, such as https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/workflow/detailer-for-animatediff.png and https://www.youtube.com/watch?v=LDXFOwGvjwk&ab_channel=Dr.Lt.Data'sComfyUIExtension , but I have not found a scenario that matches mine exactly.

I'm not sure if this is intended by design or if I am using it incorrectly. Could you please provide me with some suggestions?

**Comment by ltdrdata** [comment]
Have you read this?
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/detectors.md#simple-detector-for-animatediff

**Comment by Misukokonmilk** [comment]
Yes, I've seen that before, but I believe the pre-prepared mask images, which were created in a separate workflow and subsequently reviewed by me, offer greater reliability and flexibility in usage. For instance, I can generate the original video multiple times without having to re-detect the same image more than once. Therefore, I'd like to inquire if these are supported as my preferred option.

I am going to try the 'Simple Detector For AnimateDiff' and opt for 'Combine neighboring frames'. Once again, I appreciate your nodes, demos and videos, they've been extremely helpful.

**Comment by ltdrdata** [comment]
Ah, so you want to directly convert batch masks into SEGS and input them? That feature is not currently supported, but I will implement it.

**Comment by Misukokonmilk** [comment]
That would be great, I am extremely grateful and eagerly anticipating this feature.

**Comment by ltdrdata** [comment]
`MaskToSEGS for AnimateDiff` is updated.
Now you can pass mask batch.
