### ISSUE TITLE
Suggestion: Add wildcard file reload without restarting server

### ISSUE THREAD

**Issue by wutipong** [ltdrdata/ComfyUI-extension-tutorials#46]
Currently, after making changes to wildcard file, the changes are not applied to neither Wildcard Processor node nor Wildcard Encode. Reloading the browser does not help.  

This make working with wildcard file difficult as one would have to restart the server everytime the wildcard file is changed.

It'd be nice to have a way to manually reload the cached value.

**Comment by ltdrdata** [comment]
You can reload wildcard files through `refresh` button
