### ISSUE TITLE
Wildcards file codepage

### ISSUE THREAD

**Issue by gobshyte** [ltdrdata/ComfyUI-extension-tutorials#5]
The wildcard node does not seem to support UTF8, I think it is using codepage 1252 to read the files, I keep getting this error:

 File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 11328: character maps to <undefined>

They go away if I convert files to CP1252.

Can it be changed to allow UTF8 text files to be read perhaps? 

A lot of artist names have accents etc. in codepage 1252, and a wildcard file with emojis is especially problematic :D

**Comment by ltdrdata** [comment]
now wildcards file supports 'utf-8'
