### ISSUE TITLE
ImpactWildcardencode randomisation/batch vram usage

### ISSUE THREAD

**Issue by BrechtCorbeel** [ltdrdata/ComfyUI-extension-tutorials#52]
How do I get it to randomize after an import it seems fixed when saved, which is good, because it means I can replicate previous images and do different versions with models of the same seed to compare but not randomise new batches, the uniqueness of the number means I need to create a program to run on the .jsons to randomise batched workflows.

**Comment by ltdrdata** [comment]
![wildcard-list](https://github.com/user-attachments/assets/986cfde2-bf57-4eb1-b393-ef4d9bb4d0d7)

You can do this.
