### ISSUE TITLE
evaluated results of wildcard does not get put into populated text field (impactwildcardencode node)

### ISSUE THREAD

**Issue by yegods** [ltdrdata/ComfyUI-extension-tutorials#56]
The wildcard file name gets put into the populated text field, instead of the results of the wildcard selection.  This is disappointing, and maybe (hopefully) a bug.  I was expecting that if the file 'colors' had the contents "red, green blue", and "red" was selected, that "red" would be placed into the populated text field, not 'colors'.  This makes the feature almost useless, for me at least.  I hope this makes sense, and that it can be fixed.  I tried looking around for an option to do that, but didn't see it.

**Comment by ltdrdata** [comment]
That means your wildcard file is incorrect and hasn't been loaded properly, or you've used the wildcard incorrectly so it doesn't match.

To diagnose that, you need to check the wildcard file, the path where the wildcard file is saved, and the entire workflow.

**Comment by yegods** [comment]
Can you explain further?  The wildcards seem to function correctly?  Or is this just confirmation bias?  The feature is supposed to work how I want... i.e. put the select text into the populated text field?

**Comment by ltdrdata** [comment]
> Can you explain further? The wildcards seem to function correctly? Or is this just confirmation bias? The feature is supposed to work how I want... i.e. put the select text into the populated text field?

Without knowing which wildcard file you saved, where you saved it, and how you configured your workflow, it's impossible to make any guesses.

**Comment by yegods** [comment]
i have a wildcard file named "hairstyles.txt", in the custom wildcards directory.  it has one hairstyle per line.  i use the simple prompt, "the woman's hairstyle is __hairstyles__".  in the populated text field it puts "the woman's hairstyle is hairstyle1|hairstyle2|...etc.  I tried also putting "the woman's hairstyle is {__hairstyles__}", but get the same result.  all the other replacements are working correctly, i.e. putting the selected random text into the populated text field... but anything from a wildcard behaves as i said.

**Comment by yegods** [comment]
i tried using the sample file 'flower', and it worked correctly.  maybe some weird formatting problem.  anyhow, i'll close this, since i've gotten a working wildcard.

**Comment by ltdrdata** [comment]
> i have a wildcard file named "hairstyles.txt", in the custom wildcards directory. it has one hairstyle per line. i use the simple prompt, "the woman's hairstyle is **hairstyles**". in the populated text field it puts "the woman's hairstyle is hairstyle1|hairstyle2|...etc. I tried also putting "the woman's hairstyle is {**hairstyles**}", but get the same result. all the other replacements are working correctly, i.e. putting the selected random text into the populated text field... but anything from a wildcard behaves as i said.

wildcard syntax is `__wildcard-name__` not `{wildcard-name}`.
`{}` is not a wildcard for loading from a file, but rather a syntax for random choice from options like `{a|b|c}`.
