### ISSUE TITLE
The A and B in LoRA Loader (Block Weight)

### ISSUE THREAD

**Issue by tiptinker** [ltdrdata/ComfyUI-extension-tutorials#57]
In this workflow
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/xyplot-lbw2.png

![image](https://github.com/user-attachments/assets/ec0d8208-e473-417d-8a51-bb61df95f172)

You set A to 1.1
but shouldn't the number range from 0 to 1 ?
What does 1.1 mean here?

**Comment by tiptinker** [comment]
And what does this text input mean?
![image](https://github.com/user-attachments/assets/7cf47529-1874-47e5-9e9a-cafebd45ef71)

**Comment by ltdrdata** [comment]
> In this workflow https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/workflow/xyplot-lbw2.png
> 
> ![image](https://private-user-images.githubusercontent.com/32961592/376014869-ec0d8208-e473-417d-8a51-bb61df95f172.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDM2NTYsIm5iZiI6MTcyODgwMzM1NiwicGF0aCI6Ii8zMjk2MTU5Mi8zNzYwMTQ4NjktZWMwZDgyMDgtZTQ3My00MTdkLThhNTEtYmI2MWRmOTVmMTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDA3MDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MDNlNjhiZWRiYzI3NDUwZmYxZGY2N2NiMmI2OTAxYjc2MWQxMTljZmFmZjU4YmVmYTk4ZjI2NTg4N2QyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UPiBIEYs-4hETs5gRR4XpT898JTsQvujfhvOxEK-aPc)
> 
> You set A to 1.1 but shouldn't the number range from 0 to 1 ? What does 1.1 mean here?

nope. the range is -10.0 to 10.0.
You can also amplify the weight of a specific block.

Amplifying the weight of the entire LoRA can significantly degrade quality, but you can mitigate this side effect by amplifying only specific blocks.

The populated_vector is literally the final calculation result of the LoRA block weight spec.
Variables like A and B are substituted with their set values.
Additionally, you can sparsely assign block weights in the form of named specs.

https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Inspire-Pack/tutorial/LoraBlockWeight.md#named-weight-syntax
