### ISSUE TITLE
"Switch any" and "Inverse Switch" automatically disconects

### ISSUE THREAD

**Issue by Nekodificador** [ltdrdata/ComfyUI-extension-tutorials#58]
Since a few days ago, the switch nodes have been disconnecting automatically when saving the workflow. I currently use them to simulate a bypass from the API (since it can't be done by default), but it has stopped working as the connections are no longer respected. In previous versions, it worked perfectly, so I don't understand what could have happened.

![before](https://github.com/user-attachments/assets/b3725e10-d326-46ff-af0d-280216ff5e8f)
![image](https://github.com/user-attachments/assets/451f253d-0874-4e6f-9467-3edf20ea2626)

**Comment by Nekodificador** [comment]
I don't know if I've found a bug or if I'm doing something wrong, but I've noticed that the nodes giving me errors were duplicated from a previous group. It seems like they have some sort of "memory," so if I duplicate one of them and it doesn't connect to the original node, it rejects new connections when the workflow is reloaded.

For now, I've managed to get it working by recreating the node combination from scratch in this order:

1. I connect the main node to the Inverse Switch, so it converts the input to the corresponding type.
2. I connect the Inverse Switch to the Switch Any, so it also acquires the same type of connection.
3. I connect the output2 to its corresponding place in the group or to a fromPipeV2 (in case I need to carry multiple connections simultaneously).
4. I reconnect the outputs or the EditPipe back to the Switch Any.

![image](https://github.com/user-attachments/assets/d62ddcec-86fa-45d5-8c12-5ecbbcbf1e2b)

If I don’t follow these exact steps in this specific order, everything breaks.

**Comment by ltdrdata** [comment]
This is fixed.

**Comment by Nekodificador** [comment]
Sorry but it keeps happening. Am I doing something wrong?
![image](https://github.com/user-attachments/assets/4dacc06a-6343-47c8-9bfe-a74de22d9502)

**Comment by ltdrdata** [comment]
> Sorry but it keeps happening. Am I doing something wrong? ![image](https://private-user-images.githubusercontent.com/51487768/377042327-4dacc06a-6343-47c8-9bfe-a74de22d9502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODI0MDYsIm5iZiI6MTcyOTA4MjEwNiwicGF0aCI6Ii81MTQ4Nzc2OC8zNzcwNDIzMjctNGRhY2MwNmEtNjM0My00N2M4LTliZmUtYTc0ZGUyMmQ5NTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDEyMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZTY4NjA3NzRhZDUyNDIzMmEwYjY2NTMyNWJlMjYzMzQxMzIxMzYxODcwYjAzZWYxZWVkOGJlMDY1YTJlNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2ROxsIdycZL24iQidbk8OyZ8I77yszd3PeYi4Q_BoF0)

First, regenerate the nodes on both sides.
They may already be internally damaged.

**Comment by Nekodificador** [comment]
I did, but some nodes are still disconnecting. It’s weird because the exact same workflow works fine when I use Pinokio WebUI, but if I open it in a browser, some groups disconnect while others stay connected. I just did a clean install of ComfyUI (not using Pinokio) and the same thing happens.

**Comment by Nekodificador** [comment]
Oh, I just found the problem! When I deploy a workflow outside of my own computer and images aren't loaded, it breaks the connections. For now, I'm using _example.png_ as a placeholder, but if someone has deleted it from their ComfyUI base, the bypass technique fails. It's weird because those images aren’t even being processed yet, but internally, the Inverse Switches changes to "INT" mode instead of "Basic Pipe," and it doesn't let you reconnect it to its previous node.

![image](https://github.com/user-attachments/assets/4d728635-cbaf-453d-bfcb-847be186ca23)
