### ISSUE TITLE
[Question] I get all of this except.....

### ISSUE THREAD

**Issue by Wprussell** [ltdrdata/ComfyUI-extension-tutorials#59]
I get all of this except how exactly does the regional sampler differ from the advanced regional sampler? Specifically why does the regional sampler return the image background, whereas the advanced regional sampler is background free? This one's really a head scratcher for me.

Please advise.

**Comment by ltdrdata** [comment]
The relationship between Regional Sampler and Regional Sampler Advanced is similar to the relationship between KSampler and KSampler Advanced.

The difference lies in whether you control it with denoise or with `start_step` and `end_step`.
If you are unfamiliar with the concept of KSampler Advanced, I recommend the following article.
(You can use translator)
https://comfyui.creamlab.net/guides/f_KSamplerAdvanced_denoise
