### ISSUE TITLE
Wildcards [object Promise]

### ISSUE THREAD

**Issue by gobshyte** [ltdrdata/ComfyUI-extension-tutorials#6]
The wildcard nodes generate text in the lower part of window ok, but the output node won't produce any string except:

[object Promise]

Is this a known issue?

**Comment by ltdrdata** [comment]
Currently wildcard is experiencing with presetText.js of pythongosssss.

This issue will be solved when you update to recent version of his scripts.
But, it will introduce new issue now.

Wildcard will work well, however you cannot see what is populated on there. You should remove presetText.js, for now.

I need to figure out the solution.

**Comment by gobshyte** [comment]
Ah I just found a comment on github here to the same effect!
https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/f9e002e023105997ed097ce7605bca1e6b533485

I have removed this now:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts

As I was mostly just using it to allow me extract the wildcard prompt generated from the WAS wildcard implementation anyway. (I'm trying to change from WAS wildcards to impact as seems to have better features)

Is working great now, many thanks
