### ISSUE TITLE
Why are the tutorials labeled "LEGACY"? Are they no longer usable? And is this extension supposed to be installed?

### ISSUE THREAD

**Issue by ClothingAI** [ltdrdata/ComfyUI-extension-tutorials#60]
Hello
I just found this repo and it has this title: 
**Tutorials (LEGACY)**

Are we not supposed to use these?
and if yes, then what to use?

__

is this an extension supposed to be installed? I don't see it in the manager.

**Comment by ltdrdata** [comment]
I am rewriting tutorials.

**Comment by ClothingAI** [comment]
> I am rewriting tutorials.

OK in the meantime, don't remove them please. Keep them.

**Comment by ltdrdata** [comment]
> > I am rewriting tutorials.
> 
> OK in the meantime, don't remove them please. Keep them.

Oh, there are no plans to remove the existing documents.
It's just that the previously written documents were not organized, so I was in the process of writing them while making them more organized.
