### ISSUE TITLE
RegionalSampler with SD35

### ISSUE THREAD

**Issue by fedor-evolox** [ltdrdata/ComfyUI-extension-tutorials#62]
Expected Behaviour:
using RegionalSampler with SD35 to apply LoRA to masked region

Actual Behaviour:
The size of tensor a (4) must match the size of tensor b (16) at non-singleton dimension 1

Attached Workflow:
![RegionalSampler_SD35](https://github.com/user-attachments/assets/bc2d421b-d623-45bd-8113-8264999b1809)

**Comment by ltdrdata** [comment]
Make sure your Impact Pack is up to date.

**Comment by fedor-evolox** [comment]
> Make sure your Impact Pack is up to date.

It is up to date, but one part (upper) is not working. And second part of workflow (at the bottom) is working perfectly 
![image](https://github.com/user-attachments/assets/06f21c19-de1f-4ca2-a69e-75aaee8abe4f)

**Comment by ltdrdata** [comment]
It's v7.10.7. right?
I can't reproduce this issue on my end because it was fixed quite a while ago.

Another alternative solution is to use EmptySD3LatentImage instead of EmptyLatentImage.

![image](https://github.com/user-attachments/assets/58c9e638-e505-49bd-8c7a-c450595721ad)
