### ISSUE TITLE
Where are the "rp-mask" input images you are using in the example workflow "regionalsampling.png"?

### ISSUE THREAD

**Issue by moreAImore** [ltdrdata/ComfyUI-extension-tutorials#63]
Hello, 
I trying your awesome lenghtly collection of workflows, I thought I can try to re learn region prompting in comfy, except your input image example are ABSENT. Screenshot:

![image](https://github.com/user-attachments/assets/f428f95f-36d6-4d5f-8168-e798359b7a99)

Could you provide me the images please?
(And see if there any other missing, I am gonna go through more workflow examples possible)
Thanks

**Comment by ltdrdata** [comment]
![rp-mask1](https://github.com/user-attachments/assets/e11b3aaf-fcb9-425b-94f7-6fc47b612093)
![rp-mask2](https://github.com/user-attachments/assets/307804aa-3dc5-4af2-b83d-c3a0cd523d4c)
![rp-mask3](https://github.com/user-attachments/assets/98a0738c-4eff-49c8-859a-9484d7170cd1)
![rp-mask4](https://github.com/user-attachments/assets/11966b1a-edd0-4f2e-8fd0-b876f6b5c95b)
![rp-mask5](https://github.com/user-attachments/assets/45e0bf3b-b3e3-4890-a899-c23d31ee9073)

**Comment by moreAImore** [comment]
Thank you. So they are indeed missing I see.
