### ISSUE TITLE
ImpactWildcardProcessor can't take "seed" as input, only as widget

### ISSUE THREAD

**Issue by refurrify** [ltdrdata/ComfyUI-extension-tutorials#64]
works great with "seed" as widget, but when I convert to input, and give it an integer, nothing happens. I tried "WAS Suite>number>seed", using "int" as input to ImpactWildcardProcessor. Also tried

**Comment by ltdrdata** [comment]
In that case, you need to change the mode to "fixed" and use populated input instead of wildcard input.
