### ISSUE TITLE
Any way to combine BBOX or SEGS nodes?

### ISSUE THREAD

**Issue by Sorry-Im-Stupid** [ltdrdata/ComfyUI-extension-tutorials#65]
I've been wondering if there's a way to feed multiple BBOX Uralytics nodes or SEGS outputs into the same detailer, or at least to load them sequentially without having to Load, Unload, re-load, etc... for each one.

The way I've tried it from a workflow I was given is very inefficient and always fills up my RAM, usually crashing after a few images.

The closest I've managed is this:
![counter selector](https://github.com/user-attachments/assets/d09f2264-395b-4830-9530-a331a3758c49)
Which will go through and use a different bbox input for each image I generate, but of course I would like it to go through and do each step to the same image until it goes through them all. 

Is this possible, or am I just barking up the wrong tree?

**Comment by ltdrdata** [comment]
![image](https://github.com/user-attachments/assets/02bcb0d1-2048-4093-ade2-b92604203c86)

You can use `SEGS Concat`
