### ISSUE TITLE
Missing Node Types : LoraLoaderBlockWeight, UltralyticsDetectorProvider

### ISSUE THREAD

**Issue by lilly1987** [ltdrdata/ComfyUI-extension-tutorials#66]
I updated everything today. I don't know what to use because I don't have that node.

```
Missing Node Types

When loading the graph, the following node types were not found

    LoraLoaderBlockWeight //Inspire
    UltralyticsDetectorProvider
```

**Comment by ltdrdata** [comment]
`LoraLoaderBlockWeight //Inspire` is belongs to `ComfyUI-Inspire-Pack`
`UltralyticsDetectorProvider` is belongs to `ComfyUI-Impact-Subpack`
