### ISSUE TITLE
Facedetailer broken

### ISSUE THREAD

**Issue by Kwisss** [ltdrdata/ComfyUI-extension-tutorials#8]
![bug](https://github.com/ltdrdata/ComfyUI-extension-tutorials/assets/68794249/83c4a977-7be6-46af-b53e-6533bdec5b48)

I don't know what I did, but the mask does not look like it used too.
could this be related to updating comfyui?

**Comment by ltdrdata** [comment]
Is it old workflow? 
In that case remove the node and generate new one
Otherwise share your work to me. I'll check it.

**Comment by Kwisss** [comment]
There where no errors in the console as far as I could tell at first, but I missed the line: Loads SAM model: None (device:AUTO).
I confirmed that the was model missing by simply clicking on it in my project, After downloading the model in the menu and restarting Comfyui it worked.

Sorry for the inconvenience of the oversight on my part, It would be better if the UI visually indicated that the model was missing but I'm sure that would be for Comfyui itself to change.

Thanks for your rapid response, This can be closed I guess.

**Comment by ltdrdata** [comment]
I should come up with a solution for such issues soon.
