### ISSUE TITLE
error testing sdx+sd1.5+sdxrefiner full workflow

### ISSUE THREAD

**Issue by sanromd** [ltdrdata/ComfyUI-extension-tutorials#9]
I want to replicate the results in your [tutorial](https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Experimental/sdxl-reencode/exp1.md). However, I get an error stating, `Non-installed custom nodes are being used within the component. {'Subtract', 'Multiply', 'Floor', 'Int to float'}`. I am new to ComfyUI. I installed nodes _simple math, workflow component,_ and_impact pack_. What am I missing?

Thank you

**Comment by ltdrdata** [comment]
They are Derfuu modded nodes.

https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes

You can install them ComfyUI-Mananger's "install missing custom nodes" menu.
